language: python
python:
  - "2.7"
branches:
  only:
    - master
    - /^dev.*$/
virtualenv:
  system_site_packages: true
before_install:
 # Fix for python-gdal errors on Travis from:
 # https://github.com/travis-ci/travis-ci/issues/2401
 - sudo rm /etc/apt/sources.list.d/ubuntugis-stable-source.list
 - sudo apt-get install -qq python-numpy python-scientific
 - sudo apt-get install -qq python-shapely
 - sudo apt-get install -qq python-gdal
 - sudo apt-get install -qq python-qt4
 - sudo apt-get install -qq proj
 - sudo apt-get install -qq gmsh
 - sudo apt-get install -qq gmt
 #- sudo apt-get install -qq blender python-shapely grass qgis-plugin-grass thuban gmt gpsbabel gpx2shp python-mapscript postgis python-gdal proj libterralib
 #- sudo apt-get install -qq qgis
#install:
script: make test

